name: Acceso a data protegida

on: push

jobs:
  acceso-a-la-base-eclutamiento:
    runs-on: ubuntu-latest

    steps:
      - name: El agente llega a la fortaleza
        run: |
          echo "Agente ${{github.actor}}"
          echo ""
          echo "Buscar los archivos de la legión"
          ls -la
          echo ""
          echo ""
          echo "❌ pero qué pasó? no hay nada"
