name: Acceso a data protegida

on: push

jobs:
  acceso-a-la-base-eclutamiento:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el repositorio
        uses: actions/checkout@v4

      - name: El agente llega a la fortaleza
        run: |
          echo "Agente ${{github.actor}}"
          echo ""
          echo "Buscar los archivos de la legión"
          ls -la
          echo ""
          echo ""
          echo "✅ ¡Ahora sí hay archivos!"

      - name: 'Ahora si, vamos a ver planes'
        run: |
          echo "Buscar los archivos de la legión"
          ls -la
          echo "✅ Funciona"
          echo ""
          echo "Planes:"
          ls planes/
          echo "Villanos:"
          ls miembros/
          echo "Inteligencia"
          ls inteligencia/