# This is a basic workflow to help you get started with Actions

name: Comunicador de la legion

on:
  workflow_dispatch:
    inputs:
      villano:
        description: "Qué villano envia el mensaje?"
        required: true
        type: choice
        options:
          - Lex Luthor
          - Magneto
          - Spiderman
      mensaje:
        description: "Mensaje para el consejo"
        required: true
        default: "La misión fue un éxito"
      cow_character:
        description: "Elige qué opcion de cowsay utilizar"
        required: true
        type: choice
        options:
          - armadillo
          - dragon
          - cat
          - ghostbusters
      prioridad:
        description: "Nivel de prioridad"
        required: true
        type: choice
        options:
          - Alta 🔴
          - Media 🟡
          - Baja

jobs:
  transmitir-mensaje:
    runs-on: ubuntu-latest      

    steps:
      - name: Instalar el paquete de la legion
        run: sudo apt-get install -y cowsay


      - name: Imprimir inputs
        run: |
          echo "==========================="
          echo "         Inputs: "
          echo "==========================="
          echo ""
          echo "De: ${{inputs.villano}}"
          echo ""
          echo "Fecha: $(date -u +"%d/%m/%Y - %H:%M UTC")"
          echo "-------- Mensaje ---------"
          cowsay -f "${{inputs.cow_character}}" "${{inputs.mensaje}}"
          echo ""
          echo "--- ${{inputs.villano}}"
          echo "..."