# This is a basic workflow to help you get started with Actions

name: Comunicador de la legion

on:
  workflow_dispatch:
    inputs:
      villano: 
        description: "Qué villano envia el mensaje?"
        required: true
        type: choice
        options:
          - Lex Luthor
          - Magneto 
          - Spiderman
      mensaje: 
            description: 'Mensaje para el consejo'
            required: true
            default: 'La misión fue un éxito'
      prioridad:
        description: 'Nivel de prioridad'
        required: true
        type: choice
        options:
          - Alta 🔴
          - Media 🟡
          - Baja 
          

jobs:
  transmitir-mensaje:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

